export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export type FETCH_BOOKS_SUCCESS = typeof FETCH_BOOKS_SUCCESS;

export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';
export type FETCH_BOOKS_ERROR = typeof FETCH_BOOKS_ERROR;

export const FETCHING_BOOKS = 'FETCHING_BOOKS';
export type FETCHING_BOOKS = typeof FETCHING_BOOKS;

export const FETCH_SUBJECTS_SUCCESS = 'FETCH_SUBJECTS_SUCCESS';
export type FETCH_SUBJECTS_SUCCESS = typeof FETCH_SUBJECTS_SUCCESS;

export const FETCH_SUBJECTS_ERROR = 'FETCH_SUBJECTS_ERROR';
export type FETCH_SUBJECTS_ERROR = typeof FETCH_SUBJECTS_ERROR;

export const FETCHING_SUBJECTS = 'FETCHING_SUBJECTS';
export type FETCHING_SUBJECTS = typeof FETCHING_SUBJECTS;
